apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: microwallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: google-registry-key
      containers:
      - name: backend
        image: asia-southeast1-docker.pkg.dev/microwallet-495518/microwallet-repo/backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: microwallet-secrets
              key: DB_CONNECTION_STRING
        - name: ConnectionStrings__Redis
          valueFrom:
            secretKeyRef:
              name: microwallet-secrets
              key: REDIS_CONNECTION
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: microwallet
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
